<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    public function run()
    {
        $foods = [
            // Sumber Karbohidrat (id_kategori: 1)
            [
                'id_kategori' => 1,
                'nama_makanan' => 'Nasi Putih',
                'kalori' => 175,
                'protein' => 3.5,
                'karbohidrat' => 38,
                'lemak' => 0.3,
                'serat' => 0.4,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'kalsium' => 2,
                'zat_besi' => 0.2,
                'satuan' => '100g',
                'deskripsi' => 'Nasi putih yang sudah matang',
            ],
            [
                'id_kategori' => 1,
                'nama_makanan' => 'Roti Tawar',
                'kalori' => 265,
                'protein' => 8,
                'karbohidrat' => 49,
                'lemak' => 3.2,
                'serat' => 2.7,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'kalsium' => 20,
                'zat_besi' => 3.6,
                'satuan' => '100g',
                'deskripsi' => 'Roti tawar putih',
            ],
            [
                'id_kategori' => 1,
                'nama_makanan' => 'Kentang',
                'kalori' => 77,
                'protein' => 2,
                'karbohidrat' => 17,
                'lemak' => 0.1,
                'serat' => 2.2,
                'vitamin_a' => 0,
                'vitamin_c' => 19.7,
                'kalsium' => 12,
                'zat_besi' => 0.8,
                'satuan' => '100g',
                'deskripsi' => 'Kentang segar',
            ],

            // Sumber Protein Hewani (id_kategori: 2)
            [
                'id_kategori' => 2,
                'nama_makanan' => 'Ikan Salmon',
                'kalori' => 208,
                'protein' => 22,
                'karbohidrat' => 0,
                'lemak' => 13,
                'serat' => 0,
                'vitamin_a' => 149,
                'vitamin_c' => 3.9,
                'kalsium' => 9,
                'zat_besi' => 0.3,
                'satuan' => '100g',
                'deskripsi' => 'Ikan salmon segar',
            ],
            [
                'id_kategori' => 2,
                'nama_makanan' => 'Daging Sapi',
                'kalori' => 250,
                'protein' => 26,
                'karbohidrat' => 0,
                'lemak' => 17,
                'serat' => 0,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'kalsium' => 18,
                'zat_besi' => 2.6,
                'satuan' => '100g',
                'deskripsi' => 'Daging sapi tanpa lemak',
            ],
            [
                'id_kategori' => 2,
                'nama_makanan' => 'Telur Ayam',
                'kalori' => 155,
                'protein' => 12.6,
                'karbohidrat' => 0.6,
                'lemak' => 11.3,
                'serat' => 0,
                'vitamin_a' => 160,
                'vitamin_c' => 0,
                'kalsium' => 56,
                'zat_besi' => 1.8,
                'satuan' => '100g',
                'deskripsi' => 'Telur ayam negeri',
            ],

            // Sumber Protein Nabati (id_kategori: 3)
            [
                'id_kategori' => 3,
                'nama_makanan' => 'Tahu',
                'kalori' => 76,
                'protein' => 8,
                'karbohidrat' => 1.9,
                'lemak' => 4.8,
                'serat' => 0.3,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'kalsium' => 350,
                'zat_besi' => 5.4,
                'satuan' => '100g',
                'deskripsi' => 'Tahu putih',
            ],
            [
                'id_kategori' => 3,
                'nama_makanan' => 'Tempe',
                'kalori' => 192,
                'protein' => 20.3,
                'karbohidrat' => 7.7,
                'lemak' => 10.8,
                'serat' => 1.4,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'kalsium' => 111,
                'zat_besi' => 4.9,
                'satuan' => '100g',
                'deskripsi' => 'Tempe kedelai',
            ],

            // Sayuran (id_kategori: 4)
            [
                'id_kategori' => 4,
                'nama_makanan' => 'Bayam',
                'kalori' => 23,
                'protein' => 2.9,
                'karbohidrat' => 3.6,
                'lemak' => 0.4,
                'serat' => 2.2,
                'vitamin_a' => 469,
                'vitamin_c' => 28.1,
                'kalsium' => 99,
                'zat_besi' => 2.7,
                'satuan' => '100g',
                'deskripsi' => 'Bayam hijau segar',
            ],
            [
                'id_kategori' => 4,
                'nama_makanan' => 'Brokoli',
                'kalori' => 34,
                'protein' => 2.8,
                'karbohidrat' => 6.6,
                'lemak' => 0.4,
                'serat' => 2.6,
                'vitamin_a' => 623,
                'vitamin_c' => 89.2,
                'kalsium' => 47,
                'zat_besi' => 0.7,
                'satuan' => '100g',
                'deskripsi' => 'Brokoli segar',
            ],

            // Buah-buahan (id_kategori: 5)
            [
                'id_kategori' => 5,
                'nama_makanan' => 'Pisang',
                'kalori' => 89,
                'protein' => 1.1,
                'karbohidrat' => 22.8,
                'lemak' => 0.3,
                'serat' => 2.6,
                'vitamin_a' => 3,
                'vitamin_c' => 8.7,
                'kalsium' => 5,
                'zat_besi' => 0.3,
                'satuan' => '100g',
                'deskripsi' => 'Pisang matang',
            ],
            [
                'id_kategori' => 5,
                'nama_makanan' => 'Apel',
                'kalori' => 52,
                'protein' => 0.3,
                'karbohidrat' => 13.8,
                'lemak' => 0.2,
                'serat' => 2.4,
                'vitamin_a' => 3,
                'vitamin_c' => 4.6,
                'kalsium' => 6,
                'zat_besi' => 0.1,
                'satuan' => '100g',
                'deskripsi' => 'Apel merah segar',
            ],

            // Susu dan Produk Olahan (id_kategori: 6)
            [
                'id_kategori' => 6,
                'nama_makanan' => 'Susu Sapi',
                'kalori' => 66,
                'protein' => 3.3,
                'karbohidrat' => 4.8,
                'lemak' => 3.6,
                'serat' => 0,
                'vitamin_a' => 46,
                'vitamin_c' => 1,
                'kalsium' => 113,
                'zat_besi' => 0.1,
                'satuan' => '100ml',
                'deskripsi' => 'Susu sapi segar',
            ],
            [
                'id_kategori' => 6,
                'nama_makanan' => 'Yogurt',
                'kalori' => 59,
                'protein' => 3.5,
                'karbohidrat' => 4.7,
                'lemak' => 3.3,
                'serat' => 0,
                'vitamin_a' => 27,
                'vitamin_c' => 0.5,
                'kalsium' => 121,
                'zat_besi' => 0.1,
                'satuan' => '100g',
                'deskripsi' => 'Yogurt plain',
            ],
        ];

        foreach ($foods as $food) {
            Food::create($food);
        }
    }
}
